# Generated by Django 4.2 on 2024-04-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_flan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='price',
            field=models.IntegerField(),
        ),
    ]
