# Generated by Django 4.2 on 2024-04-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_flan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='flan_pay',
            field=models.URLField(default='https://mpago.la/2KbVDv4'),
        ),
    ]
